name: phpstan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    name: PHPStan

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: composer:v2

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-8.4-${{ hashFiles('composer.json') }}
          restore-keys: composer-8.4-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run PHPStan
        run: composer analyse
